import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

const read = (path: string) => readFile(new URL(`../../${path}`, import.meta.url), "utf8");

test("Monster Master loads the pinned Pixi renderer and deterministic generated art before gameplay", async () => {
  const launcher = await read("public/auth-launcher.js");
  const pixiSource = await read("src/browser/monster-master-pixi-entry.js");
  const pixiBridge = await read("public/monster-master-pixi-bridge.js");
  const pixiStyles = await read("public/monster-master-pixi.css");
  const pixiBundle = await read("public/monster-master-pixi-bundle.js");
  const legacyProjection = await read("public/monster-master-rotation.js");
  const manifest = JSON.parse(await read("public/assets/monster-master/manifest.json"));
  const creatureAtlas = await read("public/assets/monster-master/creature-atlas-v1.svg");
  const terrainAtlas = await read("public/assets/monster-master/terrain-atlas-v1.svg");
  const packageJson = JSON.parse(await read("package.json"));

  assert.match(launcher, /entry === "\/monster-master-app\.js"/);
  assert.ok(launcher.indexOf("monster-master-pixi-bridge.js") < launcher.indexOf("monster-master-pixi-bundle.js"));
  assert.ok(launcher.indexOf("monster-master-pixi-bundle.js") < launcher.indexOf("monster-master-correction.js"));
  assert.ok(launcher.indexOf("monster-master-overlay-guard.js") < launcher.indexOf("await import(entry)"));
  assert.doesNotMatch(launcher, /monster-master-art\.js/);
  assert.doesNotMatch(launcher, /monster-master-terrain\.js/);
  assert.doesNotMatch(launcher, /monster-master-polish\.js/);

  assert.match(pixiSource, /from "pixi\.js"/);
  assert.match(pixiSource, /preference: "webgl"/);
  assert.match(pixiSource, /autoStart: false/);
  assert.match(pixiSource, /resolution: Math\.min/);
  assert.match(pixiSource, /viewSignature/);
  assert.match(pixiSource, /diagnosticsSignature/);
  assert.match(pixiSource, /const ready = initialize\(\)\.then/);
  assert.match(pixiSource, /creature-atlas-v1\.svg/);
  assert.match(pixiSource, /terrain-atlas-v1\.svg/);
  assert.match(pixiSource, /const terrain = new Container/);
  assert.match(pixiSource, /const highlights = new Graphics/);
  assert.match(pixiSource, /const unitsLayer = new Container/);
  assert.match(pixiSource, /function terrainSignature/);
  assert.match(pixiSource, /function unitSignature/);
  assert.match(pixiSource, /requestAnimationFrame\(render\)/);
  assert.match(pixiSource, /window\.gameFrameMonsterPixi/);

  assert.match(pixiBridge, /monster-master-pixi\.css/);
  assert.match(pixiBridge, /gameframe:monster-master-coordinate/);
  assert.match(pixiBridge, /dispatchLegacyCoordinate/);
  assert.match(pixiBridge, /window\.gameFrameMonsterProjection/);
  assert.match(pixiStyles, /monster-master-pixi-canvas/);
  assert.match(pixiStyles, /monster-master-legacy-canvas/);
  assert.match(pixiStyles, /visibility: hidden/);
  assert.match(pixiBundle, /Generated by scripts\/build-monster-master-pixi\.mjs; PixiJS 8\.19\.0/);
  assert.match(legacyProjection, /LegacyProjection = Object\.freeze\(\{ disabled: true \}\)/);

  assert.match(creatureAtlas, /data:image\/webp;base64,/);
  assert.match(terrainAtlas, /data:image\/webp;base64,/);
  assert.equal(manifest.version, 2);
  assert.equal(manifest.creatures["warden-master-v1"].role, "master");
  assert.equal(manifest.creatures["stone-bulwark-v1"].role, "bulwark");
  assert.equal(manifest.creatures["emberling-skirmisher-v1"].role, "emberling");
  assert.equal(manifest.terrain["floor-a"].semantic, "floor");
  assert.equal(manifest.terrain["difficult-rootstone"].semantic, "difficult");
  assert.equal(manifest.terrain["wall-rubble-a"].semantic, "wall");
  assert.equal(manifest.terrain["central-command-shrine"].semantic, "objective");

  assert.equal(packageJson.dependencies["pixi.js"], "8.19.0");
  assert.equal(packageJson.scripts["build:monster-master-pixi"], "node scripts/build-monster-master-pixi.mjs");
  assert.equal(packageJson.scripts["check:monster-master-pixi"], "node scripts/build-monster-master-pixi.mjs --check");
  assert.match(packageJson.scripts.validate, /check:monster-master-pixi/);
  assert.match(packageJson.scripts["check:browser"], /public\/monster-master-pixi-bundle\.js/);
  assert.match(packageJson.scripts["check:browser"], /public\/monster-master-pixi-bridge\.js/);
});
