import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

const read = (path: string) => readFile(new URL(`../../${path}`, import.meta.url), "utf8");

test("the player shell separates Home activity from Games and exposes Matches, Leaderboard, and Profile", async () => {
  const launcher = await read("public/auth-launcher.js");
  const navigation = await read("public/gameframe-nav.js");
  const navigationStyles = await read("public/gameframe-nav.css");
  const navigationIntegrations = await read("public/gameframe-nav-integrations.css");
  const finalPolish = await read("public/gameframe-final-polish.css");
  const sessionOverride = await read("public/gameframe-session-override.css");
  const hub = await read("public/game-hub.js");
  const homeDashboard = await read("public/home-dashboard.js");
  const matches = await read("public/matches-app.js");
  const profile = await read("public/profile-app.js");
  const hubStyles = await read("public/game-hub.css");
  const hubShellStyles = await read("public/game-hub-shell.css");
  const hubCardStyles = await read("public/game-hub-cards.css");
  const hubFlowStyles = await read("public/game-hub-flow.css");
  const hubRpgStyles = await read("public/game-hub-rpg.css");
  const rolePlayingGames = await read("public/gameframe-rpg.html");
  const battleSimulator = await read("public/battle-simulator.html");
  const packageJson = JSON.parse(await read("package.json"));

  assert.ok(launcher.indexOf("gameframe-nav.js") < launcher.indexOf("game-hub.js"));
  assert.ok(launcher.indexOf("game-hub.js") < launcher.indexOf("await import(entry)"));
  assert.match(navigation, /data-gameframe-home/);
  assert.match(navigation, /data-gameframe-games/);
  assert.match(navigation, /data-gameframe-matches/);
  assert.match(navigation, /data-gameframe-leaderboard/);
  assert.match(navigation, /data-gameframe-profile/);
  assert.match(navigation, /href="\/\?catalog=1"/);
  assert.match(navigation, /href="\/matches\.html"/);
  assert.match(navigation, /href="\/leaderboard\.html"/);
  assert.match(navigation, /Leaderboard/);
  assert.doesNotMatch(navigation, /Hall of Fame/);
  assert.match(navigation, /href="\/profile\.html"/);
  assert.doesNotMatch(navigation, /Achievements/);
  assert.match(navigation, /gameframe-nav-integrations\.css/);
  assert.match(navigation, /gameframe-final-polish\.css/);
  assert.match(navigation, /gameframe-session-override\.css/);
  assert.match(navigation, /gameframe-shared-match-running/);
  assert.match(navigation, /stays saved in Matches/);
  assert.doesNotMatch(navigation, /stylesheet !== document\.head\.lastElementChild/);
  assert.match(navigationStyles, /position: sticky/);
  assert.match(navigationStyles, /gameframe-destination-session-space/);
  assert.match(navigationIntegrations, /gameframe-monster-route/);
  assert.match(navigationIntegrations, /gameframe-shared-match-running/);
  assert.match(navigationIntegrations, /tic-noir-topbar/);
  assert.match(finalPolish, /grid-template-columns: 38px minmax\(0, 1fr\) auto/);
  assert.match(finalPolish, /gameframe-game-hub-lobby \.section-heading/);
  assert.match(finalPolish, /gameframe-game-menu \.game-menu-hero/);
  assert.match(finalPolish, /gameframe-session-badge/);
  assert.match(sessionOverride, /gameframe-has-destination-bar\.monster-master-match-active/);
  assert.match(sessionOverride, /display: grid !important/);

  assert.match(hub, /const catalogMode = parameters\.get\("catalog"\) === "1"/);
  assert.match(hub, /import\("\.\/home-dashboard\.js"\)/);
  assert.match(hub, /sectionLabel\.textContent = catalogMode \? "GAMES" : "HOME"/);
  assert.match(homeDashboard, /\/api\/me\/feed/);
  assert.match(homeDashboard, /\/api\/me\/progression/);
  assert.match(homeDashboard, /GAMER LEVEL/);
  assert.match(homeDashboard, /CONTINUE PLAYING/);
  assert.match(homeDashboard, /Browse Games/);
  assert.match(homeDashboard, />Leaderboard<\/a>/);
  assert.match(matches, /\/api\/me\/feed/);
  assert.match(matches, /\/api\/players/);
  assert.match(matches, /acceptChallenge/);
  assert.match(profile, /\/api\/me\/feed/);
  assert.match(profile, /\/api\/me\/progression/);
  assert.match(profile, /\/api\/players\/\$\{encodeURIComponent\(viewedPlayerId\)\}\/profile/);
  assert.match(profile, /data-private-profile/);

  assert.match(hub, /id: "role-playing-games"/);
  assert.match(hub, /href: "\/gameframe-rpg\.html"/);
  assert.match(hub, /title: "Role-Playing Games"/);
  assert.match(hub, /id: "battle-simulator"/);
  assert.match(hub, /href: "\/battle-simulator\.html"/);
  assert.match(hub, /title: "Battle Simulator"/);
  assert.match(hub, /href: "\/othello\.html"/);
  assert.match(hub, /\?game=american-checkers&menu=1/);
  assert.match(hub, /\?game=tic-tac-toe&menu=1/);
  assert.doesNotMatch(hub, /href: "\/monster-master-rpg\.html\?campaign=monster-master-staging"/);
  assert.doesNotMatch(hub, /href: "\/monster-master\.html"/);
  assert.match(hub, /document\.createElement\("a"\)/);
  assert.match(hub, /card\.href = game\.href/);
  assert.match(hub, /setAttribute\("aria-label", `Open \$\{game\.title\}`\)/);
  assert.match(hub, /class="game-card-play"/);
  assert.match(hub, />Open</);
  assert.doesNotMatch(hub, /activateLibraryCard|playLink\.click/);
  assert.match(hub, /modeGrid\.hidden = true/);
  assert.match(hub, /game-menu-hero/);
  assert.match(hub, /Choose how to play/);
  assert.match(hub, /tacticalLink\?\.remove\(\)/);
  assert.match(hub, /hero\?\.querySelector\("\.game-hub-topbar"\)\?\.remove\(\)/);
  assert.doesNotMatch(hub, /href: "\/tactical\.html"/);
  assert.doesNotMatch(hub, /href: "\/combat\.html"/);

  assert.match(rolePlayingGames, /ROLE-PLAYING GAMES/);
  assert.match(rolePlayingGames, /Monster Master RPG/);
  assert.match(rolePlayingGames, /href="\/monster-master-rpg\.html"/);
  assert.doesNotMatch(rolePlayingGames, /monster-master-rpg\.html\?campaign=/);
  assert.match(rolePlayingGames, /Create RPG/);
  assert.match(rolePlayingGames, /My Campaigns/);
  assert.match(rolePlayingGames, /Import Campaign/);

  assert.match(battleSimulator, /BATTLE SIMULATOR/);
  assert.match(battleSimulator, /Monster Master Arena Battles/);
  assert.match(battleSimulator, /href="\/monster-master\.html"/);
  assert.match(battleSimulator, /Custom Battle/);
  assert.match(battleSimulator, /Generate Battlefield/);
  assert.match(battleSimulator, /Import Battle Pack/);

  assert.match(hubStyles, /game-hub-monster/);
  assert.match(hubShellStyles, /game-hub-discord-safe/);
  assert.match(hubCardStyles, /creature-atlas-v1\.svg/);
  assert.match(hubCardStyles, /piece-solar\.svg/);
  assert.match(hubCardStyles, /text-decoration: none/);
  assert.match(hubFlowStyles, /cursor: pointer/);
  assert.match(hubFlowStyles, /game-card:focus-visible/);
  assert.match(hubFlowStyles, /game-menu-hero/);
  assert.match(hubRpgStyles, /game-card-visual-rpg/);
  assert.match(hubRpgStyles, /game-card-visual-simulator/);
  assert.match(packageJson.scripts["check:browser"], /public\/gameframe-nav\.js/);
  assert.match(packageJson.scripts["check:browser"], /public\/game-hub\.js/);
  assert.match(packageJson.scripts["check:browser"], /public\/home-dashboard\.js/);
  assert.match(packageJson.scripts["check:browser"], /public\/matches-app\.js/);
  assert.match(packageJson.scripts["check:browser"], /public\/profile-app\.js/);
});

test("Tic-Tac-Toe uses the universal destination bar and restores the shared DOM when inactive", async () => {
  const launcher = await read("public/auth-launcher.js");
  const navigation = await read("public/gameframe-nav.js");
  const navigationStyles = await read("public/gameframe-nav.css");
  const navigationIntegrations = await read("public/gameframe-nav-integrations.css");
  const finalPolish = await read("public/gameframe-final-polish.css");
  const universalStyles = await read("public/tic-tac-toe-universal.css");
  const controller = await read("public/tic-tac-toe-noir.js");
  const styles = await read("public/tic-tac-toe-noir.css");
  const packageJson = JSON.parse(await read("package.json"));

  assert.ok(launcher.indexOf("gameframe-nav.js") < launcher.indexOf("tic-tac-toe-noir.js"));
  assert.ok(launcher.indexOf("tic-tac-toe-noir.js") < launcher.indexOf("await import(entry)"));
  assert.match(navigation, /navigationTheme/);
  assert.match(navigation, /TIC-TAC-TOE/);
  assert.match(navigationStyles, /body\.tic-tac-toe-noir-running \.tic-noir-topbar/);
  assert.match(navigationStyles, /grid-template-rows: minmax\(0, 1fr\) 48px/);
  assert.match(navigationIntegrations, /\.tic-noir-topbar/);
  assert.match(finalPolish, /\.tic-noir-footer > a/);
  assert.match(finalPolish, /justify-content: flex-end/);
  assert.match(universalStyles, /grid-template-rows: minmax\(0, 1fr\) 48px/);
  assert.match(universalStyles, /grid-template-rows: auto 44px/);

  assert.match(controller, /tic-tac-toe-universal\.css/);
  assert.match(controller, /function isTicTacToeMatch/);
  assert.match(controller, /function uninstallPresentation/);
  assert.match(controller, /frame\.replaceWith\(board\)/);
  assert.match(controller, /players\.insertBefore\(playerO, matchMeta\)/);
  assert.match(controller, /if \(!active\) \{\n    uninstallPresentation\(\)/);
  assert.match(controller, /document\.querySelector\("#gameframe-destination-bar"\)/);
  assert.match(controller, /board-tic-tac-toe/);
  assert.match(controller, /tic-noir-control-rail/);
  assert.match(controller, /playerO/);
  assert.match(controller, /gameLayout\.append\(rail\)/);
  assert.match(controller, /copyInvite\?\.click/);
  assert.match(controller, /newMatch\?\.click/);
  assert.match(styles, /height: 100dvh/);
  assert.match(styles, /tic-board-breathe/);
  assert.doesNotMatch(controller, /leaderboard|friends online|rating/i);
  assert.match(packageJson.scripts["check:browser"], /public\/tic-tac-toe-noir\.js/);
});

test("Monster Master uses Pixi, a player-relative turn queue, and no duplicate renderer observers", async () => {
  const launcher = await read("public/auth-launcher.js");
  const navigationIntegrations = await read("public/gameframe-nav-integrations.css");
  const finalPolish = await read("public/gameframe-final-polish.css");
  const correction = await read("public/monster-master-correction.js");
  const correctionStyles = await read("public/monster-master-correction.css");
  const pixiSource = await read("src/browser/monster-master-pixi-entry.js");
  const packageJson = JSON.parse(await read("package.json"));

  const monsterStart = launcher.indexOf('} else if (entry === "/monster-master-app.js")');
  const monsterEnd = launcher.indexOf("} else {", monsterStart);
  const monsterBranch = launcher.slice(monsterStart, monsterEnd);
  assert.ok(monsterStart >= 0 && monsterEnd > monsterStart);
  assert.ok(monsterBranch.indexOf("monster-master-pixi-bridge.js") < monsterBranch.indexOf("monster-master-correction.js"));
  assert.ok(monsterBranch.indexOf("monster-master-correction.js") < monsterBranch.indexOf("await import(entry)"));
  assert.ok(monsterBranch.indexOf("await import(entry)") < monsterBranch.indexOf("monster-master-pixi-bundle.js"));
  assert.doesNotMatch(monsterBranch, /monster-master-overlay-guard\.js/);
  assert.doesNotMatch(monsterBranch, /monster-master-polish\.js|monster-master-terrain\.js|monster-master-art\.js/);

  assert.match(navigationIntegrations, /\.monster-master-shell > \.hero/);
  assert.match(finalPolish, /body\.gameframe-othello-route \.board-viewport/);
  assert.match(finalPolish, /#board\.board-checkers/);
  assert.match(finalPolish, /monster-master-match-topbar/);
  assert.match(finalPolish, /monster-master-exit-button/);

  assert.match(correction, /function turnOrder\(view\)/);
  assert.match(correction, /right\.initiative - left\.initiative/);
  assert.match(correction, /observation\.activeUnitId/);
  assert.match(correction, /BLUE · YOU/);
  assert.match(correction, /RED · ENEMY/);
  assert.match(correction, /dataset\.monsterFriendlySeat/);
  assert.match(correction, /const monsterViewEvent = "gameframe:monster-master-pixi-view"/);
  assert.doesNotMatch(correction, /installCanvasColorRemap/);
  assert.doesNotMatch(correction, /window\.fetch = async/);
  assert.match(correction, /combat-nav a\[href="\/combat\.html"\]/);
  assert.match(correctionStyles, /monster-master-turn-unit\.is-friendly/);
  assert.match(correctionStyles, /monster-master-turn-unit\.is-enemy/);
  assert.match(correctionStyles, /monster-master-roster-rail > \.tactical-player-grid/);

  assert.match(pixiSource, /function subscribeToController/);
  assert.match(pixiSource, /autoStart: false/);
  assert.match(pixiSource, /preference: "webgl"/);
  assert.match(packageJson.scripts["check:browser"], /public\/monster-master-correction\.js/);
  assert.match(packageJson.scripts["check:monster-master-pixi"], /build-monster-master-pixi/);
});
