import assert from "node:assert/strict";
import test from "node:test";
import { access, readFile } from "node:fs/promises";
import { constants } from "node:fs";

const read = (path: string) => readFile(new URL(`../../${path}`, import.meta.url), "utf8");

async function exists(path: string): Promise<boolean> {
  try {
    await access(new URL(`../../${path}`, import.meta.url), constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

test("Discord Activity client uses the pinned official SDK through a reproducible local bundle", async () => {
  const packageJson = JSON.parse(await read("package.json"));
  const packageLock = JSON.parse(await read("package-lock.json"));
  const buildScript = await read("scripts/build-activity-bundle.mjs");
  const source = await read("src/browser/discord-activity-bootstrap.ts");
  const client = await read("src/auth/discord-activity-client.ts");
  const browserGate = await read("public/gameframe-auth.js");
  const bundle = await read("public/discord-activity-bootstrap.js");
  const notices = await read("THIRD_PARTY_NOTICES.md");

  assert.equal(packageJson.devDependencies["@discord/embedded-app-sdk"], "2.5.0");
  assert.equal(packageJson.devDependencies.esbuild, "0.28.1");
  assert.equal(packageLock.packages[""].devDependencies["@discord/embedded-app-sdk"], "2.5.0");
  assert.equal(packageLock.packages[""].devDependencies.esbuild, "0.28.1");
  assert.equal(packageJson.scripts["build:activity"], "node scripts/build-activity-bundle.mjs");
  assert.equal(packageJson.scripts["check:activity"], "node scripts/build-activity-bundle.mjs --check");
  assert.match(packageJson.scripts["validate:core"], /npm run check:activity/);
  assert.match(packageJson.scripts.validate, /npm run validate:core/);

  assert.match(source, /@discord\/embedded-app-sdk/);
  assert.match(source, /new DiscordSDK\(clientId\)/);
  assert.match(client, /sdk\.ready\(\)/);
  assert.match(client, /commands\.authorize/);
  assert.match(client, /commands\.authenticate/);
  assert.match(client, /exchange\.session\.playerId !== `discord:\$\{discordUserId\}`/);
  assert.doesNotMatch(client, /MatchSession|applyAction|legalActions/);

  assert.match(buildScript, /bundle: true/);
  assert.match(buildScript, /platform: "browser"/);
  assert.match(buildScript, /committed Discord Activity bundle is stale/);
  assert.match(bundle, /^\/\* Generated by scripts\/build-activity-bundle\.mjs; do not edit directly\. \*\//);
  assert.match(bundle, /bootstrapDiscordActivitySession/);
  assert.doesNotMatch(browserGate, /unpkg\.com|jsdelivr\.net|cdnjs\.cloudflare\.com/);
  assert.match(browserGate, /import\("\/discord-activity-bootstrap\.js"\)/);

  assert.match(notices, /@discord\/embedded-app-sdk/);
  assert.match(notices, /Version: `2\.5\.0`/);
  assert.match(notices, /esbuild/);
  assert.match(notices, /Version: `0\.28\.1`/);
});

test("temporary write-capable Activity bootstrap workflow is absent from the final branch", async () => {
  assert.equal(await exists(".github/workflows/activity-bundle-bootstrap.yml"), false);
});
